#ifndef FRAMEWORK_ACCEPTOR_CONNECTOR_1_0_CONFIG_HPP_
#define FRAMEWORK_ACCEPTOR_CONNECTOR_1_0_CONFIG_HPP_

namespace AcceptorConnector_1_0
{

static constexpr int INVALID_HANDLE = -1;
}

#endif /* FRAMEWORK_ACCEPTOR_CONNECTOR_1_0_CONFIG_HPP_ */
